### ISSUE TITLE
Checklist for v2.0

### ISSUE THREAD

**Issue by epistrephein** [epistrephein/Steam#15]
Ghost 1.0 is on its way and it's time to plan a major revamp of the theme for the big day.
Notably, the two most urgent things to address are code refactoring and new Ghost features.

Being this a fork, it still relies on very old code that was used as a base but never really modified, only overridden. Moreover, while some of the new features of the recent releases of Ghost are kinda useless on this theme, some are not and should be implemented.

I'll keep this issue open with a checklist to prepare for the 2.0 milestone.
Feel free to suggest a feature or report a bug by writing here or opening a new issue.

- [ ] Fix the mess the theme css has become
- [x] Remove unused fonts and cleanup font families
- [x] Fix `post-author` which is currently broken when more than 3 lines are displayed in mobile
- [ ] Add `error.hbs` to support custom 404 page
- [x] Show navigation only if active in blog settings
- [x] ~Link Facebook and Twitter profile to footer icons~
- [x] Remove extra partials if possible
- [x] Update external css/js libraries
- [x] Add all the favicons using something like [realfavicongenerator](https://realfavicongenerator.net)?
- [x] Add Code of Conduct
- [x] Add badge for latest Ghost version supported
- [x] Update installation guide in README to support zip-drop install in admin panel
- [x] Update `package.json` to follow the new standard (see [Casper](https://github.com/TryGhost/Casper/blob/master/package.json))
- [x] Move CHANGELOG to [Keep a Changelog](http://keepachangelog.com/) format
- [x] Add some screenshots both for theme submitting and README
- [ ] Resubmit theme to Ghost Marketplace from which it looks to have been disappeared 
- [ ] Add a What's New section in README when releasing v2.0
- [ ] Update demo site to latest Ghost and theme version when releasing v2.0
- [x] Secure demo site with https

**Comment by epistrephein** [comment]
Version 2.0 is live now. Still many things to fix and clean, but I will close this for now and address issues individually.
